-- Extensions utiles
create extension if not exists "pgcrypto";

-- Table des joueurs
create table if not exists public.players (
  id bigint generated by default as identity primary key,
  username_chesscom text not null unique,
  display_name text not null,
  club text not null default 'Ivoire Chess Club',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Table des paramètres applicatifs
create table if not exists public.app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.club_matches (
  id bigint generated by default as identity primary key,
  player1_username text not null references public.players(username_chesscom),
  player2_username text not null references public.players(username_chesscom),
  match_date timestamptz not null,
  format text not null,
  status text not null default 'upcoming',
  result text,
  created_at timestamptz not null default now()
);

create table if not exists public.club_tournaments (
  id bigint generated by default as identity primary key,
  title text not null,
  tournament_date date not null,
  format text not null,
  location text not null,
  description text,
  external_link text,
  status text not null default 'upcoming',
  created_at timestamptz not null default now()
);

-- Trigger pour maintenir updated_at
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists app_settings_set_updated_at on public.app_settings;
create trigger app_settings_set_updated_at
before update on public.app_settings
for each row execute function public.set_updated_at();

-- Table des admins (rattachée à auth.users)
create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- Helper pour policies
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.app_admins a
    where a.user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- RLS
alter table public.players enable row level security;
alter table public.app_settings enable row level security;
alter table public.app_admins enable row level security;
alter table public.club_matches enable row level security;
alter table public.club_tournaments enable row level security;

-- Lecture publique
drop policy if exists "players_public_read" on public.players;
create policy "players_public_read"
on public.players
for select
using (is_active = true);

drop policy if exists "settings_public_read" on public.app_settings;
create policy "settings_public_read"
on public.app_settings
for select
using (true);

drop policy if exists "matches_public_read" on public.club_matches;
create policy "matches_public_read"
on public.club_matches
for select
using (true);

drop policy if exists "tournaments_public_read" on public.club_tournaments;
create policy "tournaments_public_read"
on public.club_tournaments
for select
using (true);

-- Ecriture admin uniquement
drop policy if exists "players_admin_write" on public.players;
create policy "players_admin_write"
on public.players
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "settings_admin_write" on public.app_settings;
create policy "settings_admin_write"
on public.app_settings
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "matches_admin_write" on public.club_matches;
create policy "matches_admin_write"
on public.club_matches
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "tournaments_admin_write" on public.club_tournaments;
create policy "tournaments_admin_write"
on public.club_tournaments
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins_self_read" on public.app_admins;
create policy "admins_self_read"
on public.app_admins
for select
using (auth.uid() = user_id);

-- Valeur initiale
insert into public.app_settings(key, value)
values
  ('top_limit', '20'),
  ('reward_top_amount', '10000'),
  ('reward_progress_amount', '5000'),
  ('reward_enabled', '1'),
  ('reward_next_at', ''),
  ('ref_date_mode', 'auto'),
  ('ref_date_start', ''),
  ('ref_date_end', '')
on conflict (key) do update set value = excluded.value;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'club_matches'
  ) then
    alter publication supabase_realtime add table public.club_matches;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'club_tournaments'
  ) then
    alter publication supabase_realtime add table public.club_tournaments;
  end if;
end $$;

-- IMPORTANT: après création du compte admin via Supabase Auth, exécuter:
-- insert into public.app_admins(user_id) values ('UUID_DU_COMPTE_ADMIN');
